# Generated by Django 3.1 on 2020-08-29 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.CharField(default='Senper Graphics', max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='designs/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
            ],
        ),
    ]
