# Generated by Django 3.1 on 2020-09-22 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=100)),
                ('about_you', models.TextField()),
                ('work_at', models.CharField(blank=True, max_length=100)),
                ('skill_1', models.CharField(blank=True, max_length=100)),
                ('skill_2', models.CharField(blank=True, max_length=100)),
                ('skill_3', models.CharField(blank=True, max_length=100)),
                ('skill_4', models.CharField(blank=True, max_length=100)),
                ('skill_5', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.CharField(blank=True, max_length=100)),
                ('profile', models.ImageField(upload_to='profile_pic/')),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
                ('design_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='designs/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='designs/%Y/%m/%d/')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.designer')),
            ],
        ),
    ]
