# Generated by Django 3.1 on 2020-09-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='course_name',
            field=models.CharField(default='olaa media graphics tutorial', max_length=100),
        ),
    ]
